apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-service
  labels:
    app: posts-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-service
  template:
    metadata:
      name: posts-service
      labels:
        app: posts-service
    spec:
      containers:
        - name: posts-service
          image: officialravi22/linkedin-app-posts-service
          imagePullPolicy: IfNotPresent
          resources:
              limits:
                memory: "400Mi"
                cpu: "200m"
              requests:
                memory: "200Mi"
                cpu: "100m"
          env:
            - name: DB_USER
              value: user
            - name: DB_PASSWORD
              value: password
            - name: DB_NAME
              value: postdb
            - name: DB_SERVICE
              value: posts-db
            - name: SPRING_PROFILES_ACTIVE
              value: k8s

          ports:
            - containerPort: 9010

---
apiVersion: v1
kind: Service
metadata:
  name: posts-service
spec:
  selector:
    app: posts-service
  ports:
    - port: 80
      targetPort: 9010

    
      